### ISSUE TITLE
Azure ML 

### ISSUE THREAD

**Issue by JamboChen** [microsoft/studentambassadors#229]
### Describe the bug

ToolLoadError: Failed to load tool 'Vector Index Lookup' for node 'Vector_Index_Lookup_lomr' due to 'internal server error'.

### What happened?

The following error occurs when running the `Vector Index Lookup` node
![image](https://github.com/microsoft/studentambassadors/assets/34180719/e7049b6d-56f0-4c51-8959-e32e9bab2549)

Stack trace
```
Error: Request failed with status code 400
    at Fz (https://ml.azure.com/assets/index-80b513df.js:261:13689)
    at Iz (https://ml.azure.com/assets/index-80b513df.js:261:13877)
    at XMLHttpRequest.E (https://ml.azure.com/assets/index-80b513df.js:262:1672)
```

Client request ID: f3d3b402-d476-4d83-87c3-3ee2cbf0c838
Trace ID: 723e3ce4-c011-4051-b4a9-88e8641d4c7d

### What did you expect to happen?

The node can complete

### How would you reproduce the bug?

1. Click `Create` under the `vector index` tab of the Prompt flow
2. Upload files, choose `Faiss Index`, then click `Create`
3. Clone `Q&A with your own data using Faiss Index`
4. Copy the `Datastore URI` of vector index, and paste it on the `Vector Index Lookup`  node of Flows

### Did this happen via Desktop and/or Smartphone?

Desktop

### What browsers are you seeing the problem on?

Microsoft Edge

### Version

115.0.1901.188 

### What is your current role?

Student Ambassador

### What technical topic is this bug related to?

AI/Data Science/Machine Learning

### Relevant log output

```shell
{
  "error": {
    "code": "UserError",
    "message": "Failed to load tool 'Vector Index Lookup' for node 'Vector_Index_Lookup_lomr' due to 'internal server error'.",
    "innerError": {
      "code": "ValidationError",
      "innerError": {
        "code": "ToolValidationError",
        "innerError": {
          "code": "ToolLoadError"
        }
      }
    },
    "additionalInfo": null,
    "details": []
  },
  "correlation": {
    "operation": "80fc27b75bea4b16a36e5fbea81f1af5",
    "request": "957e4bfe2f86c7a8"
  }
}
```

**Comment by Briwalkr** [comment]
I am getting the same error on an environment that I setup yesterday. New connection to AOAI, Local Dataset(AML storage), new compute/prompt flow runtime setup (promptflow-runtime:**20230801**.v1), new faiss index created this morning. 

Using the sample flow that was created as an output of the faiss index creation, I get the following error. 

Failed to load tool 'Vector Search' for node 'search_question_from_indexed_docs' due to 'internal server error'.

Retesting - pointing the path directly to blob index/ source and then again directly pointing at the MLIndex file, and both get the following error (with a different /tmp/runSpecificTempDir/MLIndex target). It appears the file is not being moved to the expected location for the Vector Search tool. 

ToolLoadError: Failed to load tool 'Vector Search' for node 'search_question_from_indexed_docs' due to '[Errno 2] No such file or directory: '/tmp/tmpq2ysf5uj/MLIndex''.
